import { Bot } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * EU AI Act Article 50(1) disclosure (in force 2026-08-02).
 *
 * People interacting directly with an AI system must be informed, from the
 * start of the first interaction, clearly and accessibly. The obligation
 * reaches providers outside the EU whenever the output is used in the EU, so a
 * publicly reachable European Portuguese tutor is squarely in scope.
 *
 * Two rules drive the implementation:
 *
 * 1. The word "AI" appears in every variant. A product name — "Professora Ana",
 *    "Português Tutor" — is not a disclosure, however obvious it feels to us.
 * 2. Nothing is conveyed by colour or icon alone. The icon is `aria-hidden` and
 *    the sentence carries the entire meaning, so a screen reader and a
 *    monochrome display receive exactly what a sighted user receives.
 *
 * `banner` is for surfaces hosting a live conversational agent. `line` is the
 * persistent app-wide notice, rendered in the shared layout so pages that
 * generate content cannot silently omit it.
 */
export default function AiDisclosure({
  variant = "banner",
  className,
}: {
  variant?: "banner" | "line";
  children?: never;
  className?: string;
}) {
  if (variant === "line") {
    return (
      <p role="note" className={cn("tutor-ai-disclosure", className)}>
        Português Tutor uses AI. Lessons, corrections and conversations are
        generated by artificial intelligence and can be wrong.
      </p>
    );
  }

  return (
    <div
      role="note"
      aria-label="Artificial intelligence disclosure"
      className={cn(
        "flex items-start gap-2.5 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-900",
        className
      )}
    >
      <Bot className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
      <p>
        <span className="font-semibold">You are talking to an AI.</span>{" "}
        Professora Ana is an artificial-intelligence conversation partner, not a
        human teacher. She is generated by AI, can make mistakes, and should not
        be relied on as a certified language assessment.
      </p>
    </div>
  );
}
