import { describe, expect, test } from "bun:test";
import { renderToStaticMarkup } from "react-dom/server";
import AiDisclosure from "./AiDisclosure";

/**
 * ZOU-1137 — renders the disclosure for real rather than grepping the source.
 *
 * The sibling source-level test guards placement inside pages; this one proves
 * the markup a browser would receive actually carries the accessible name and
 * the explicit word "AI", so the compliance claim rests on output, not intent.
 */

function textOf(html: string): string {
  return html.replace(/<[^>]+>/gu, "").replace(/\s+/gu, " ").trim();
}

describe("AiDisclosure renders an accessible AI notice", () => {
  test("banner names AI in its text and exposes an accessible name", () => {
    const html = renderToStaticMarkup(<AiDisclosure />);
    expect(html).toContain('role="note"');
    expect(html).toContain('aria-label="Artificial intelligence disclosure"');

    const text = textOf(html);
    expect(text).toContain("You are talking to an AI.");
    expect(text).toContain("artificial-intelligence conversation partner, not a human teacher");

    // Strip every element that a screen reader ignores; the remaining text must
    // still disclose the AI. This is what "not conveyed by icon alone" means.
    const withoutHidden = textOf(html.replace(/<[^>]*aria-hidden="true"[^>]*>.*?<\/[^>]+>/gu, ""));
    expect(withoutHidden).toContain("AI");
  });

  test("line variant names AI and is a semantic note", () => {
    const html = renderToStaticMarkup(<AiDisclosure variant="line" />);
    expect(html).toContain('role="note"');
    const text = textOf(html);
    expect(text).toContain("uses AI");
    expect(text).toContain("generated by artificial intelligence and can be wrong");
  });

  test("neither variant relies on a product name alone", () => {
    for (const html of [
      renderToStaticMarkup(<AiDisclosure />),
      renderToStaticMarkup(<AiDisclosure variant="line" />),
    ]) {
      const text = textOf(html);
      const withoutProductNames = text
        .replaceAll("Professora Ana", "")
        .replaceAll("Português Tutor", "");
      expect(/\bAI\b|artificial intelligence|artificial-intelligence/iu.test(withoutProductNames)).toBe(
        true
      );
    }
  });
});
