import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * ZOU-1137 — EU AI Act Article 50(1) guards.
 *
 * These are source-level assertions rather than DOM tests because the project
 * has no browser test runtime. That is a deliberate trade: the failure being
 * guarded against is someone tidying the disclosure away during unrelated UI
 * work, which a source check catches, and the compliance obligation is too
 * cheap to leave resting on reviewer memory.
 */

const root = join(import.meta.dir, "..");
const read = (path: string) => readFileSync(join(root, path), "utf8");

describe("AI disclosure (EU AI Act Art. 50(1))", () => {
  test("both variants name AI explicitly, not just the product", () => {
    const source = read("components/AiDisclosure.tsx");
    const copy = source.slice(source.indexOf("export default"));
    // "Professora Ana" or "Português Tutor" alone is not a disclosure.
    expect(copy).toContain("You are talking to an AI.");
    expect(copy).toContain("artificial-intelligence conversation partner");
    expect(copy).toContain("uses AI");
    expect(copy).toContain("generated by artificial intelligence");
  });

  test("meaning does not depend on colour or the icon", () => {
    const source = read("components/AiDisclosure.tsx");
    // The icon is decoration; a screen reader must receive the full sentence.
    expect(source).toContain('aria-hidden="true"');
    expect(source).toContain('role="note"');
    expect(source).toContain('aria-label="Artificial intelligence disclosure"');
  });

  test("the persistent notice is mounted app-wide in the shared layout", () => {
    const source = read("components/Layout.tsx");
    expect(source).toContain('import AiDisclosure from "@/components/AiDisclosure"');
    expect(source).toContain('<AiDisclosure variant="line" />');
  });

  test("the conversational surface carries the prominent banner", () => {
    const source = read("pages/Chat.tsx");
    expect(source).toContain('import AiDisclosure from "@/components/AiDisclosure"');
    expect(source).toContain("<AiDisclosure />");
    // Must precede the controls: Art. 50(1) requires the notice from the start
    // of the first interaction, so it cannot sit below the call button.
    const banner = source.indexOf("<AiDisclosure />");
    const startCall = source.indexOf("onClick={toggleLive}");
    expect(banner).toBeGreaterThan(-1);
    expect(banner).toBeLessThan(startCall);
  });
});
